In [1]:
import pandas as pd

In [2]:
df_csv = pd.read_csv("../data/raw/games.csv")

df_csv.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [3]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122611 entries, 2539430 to 4141790
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       122610 non-null  object
 1   Name                        122611 non-null  object
 2   Release date                122611 non-null  object
 3   Estimated owners            122611 non-null  int64
 4   Peak CCU                    122611 non-null  int64
 5   Required age                122611 non-null  float64
 6   Price                       122611 non-null  int64
 7   DiscountDLC count           122611 non-null  int64
 8   About the game              114162 non-null  object
 9   Supported languages         122611 non-null  object
 10  Full audio languages        122611 non-null  object
 11  Reviews                     12070 non-null   object
 12  Header image                122530 non-null  object
 13  Website                     49676 non-null   object
 14  Support url                 54142 non-null   object
 15  Support email               100348 non-null  object
 16  Windows                     122611 non-null  bool
 17  Mac                         122611 non-null  bool
 18  Linux                       122611 non-null  bool
 19  Metacritic score            122611 non-null  int64
 20  Metacritic url              4256 non-null    object
 21  User score                  122611 non-null  int64
 22  Positive                    122611 non-null  int64
 23  Negative                    122611 non-null  int64
 24  Score rank                  40 non-null      float64
 25  Achievements                122611 non-null  int64
 26  Recommendations             122611 non-null  int64
 27  Notes                       22458 non-null   object
 28  Average playtime forever    122611 non-null  int64
 29  Average playtime two weeks  122611 non-null  int64
 30  Median playtime forever     122611 non-null  int64
 31  Median playtime two weeks   122611 non-null  int64
 32  Developers                  114174 non-null  object
 33  Publishers                  113702 non-null  object
 34  Categories                  113658 non-null  object
 35  Genres                      114198 non-null  object
 36  Tags                        83346 non-null   object
 37  Screenshots                 116593 non-null  object
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), object(19)
memory usage: 35.0+ MB

In [4]:
df_csv[["Name", "Genres", "Release date", "Publishers"]].head()

,Name,Genres,Release date,Publishers
2539430,"Aug 1, 2023",NaN,0 - 0,NaN
496350,"Jul 29, 2016",Adventure,0 - 20000,MangaGamer
1034400,"May 6, 2019",Casual,0 - 20000,8floor
3292190,"Oct 31, 2024","Casual,Indie,Simulation",0 - 20000,유진게임즈
3631080,"Apr 24, 2025","Action,Early Access",0 - 20000,Reality Expanded LLC

Először megvizsgáltam a .csv adatfájlt, és úgy tűnt, hogy vannak sorok, ahol az oszlopok el vannak csúszva. Az adathalmaz Kaggle oldalán találtam egy ezt megerősítő posztot is, viszont azt írták ott, hogy a JSON formátum helyesen tartalmazza az adatokat, úgyhogy inkább azzal fogok dolgozni.

In [5]:
df_json = pd.read_json("../data/raw/games.json", orient="index")

In [6]:
df_json.head()

,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,header_image,...,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0,0.00,0,,,,,https://shared.akamai.steamstatic.com/store_it...,...,0,0,0 - 0,0,0,0,0,0,0,[]
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0,5.24,0,"Springtime, April: when the cherry trees come ...","Springtime, April: when the cherry trees come ...","Spring has come, and our protagonist, Yukinari...",,https://shared.akamai.steamstatic.com/store_it...,...,252,3,0 - 20000,8,0,8,0,65,0,"{'Adventure': 27, 'Visual Novel': 19, 'Anime':..."
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0,4.99,0,"Immerse yourself in the most beloved, mystical...","Immerse yourself in the most beloved, mystical...",Discover an entrancing and spectacular world!,,https://shared.akamai.steamstatic.com/store_it...,...,21,3,0 - 20000,0,0,0,0,0,0,"{'Casual': 83, 'Card Game': 52, 'Solitaire': 4..."
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",Yuha! I'll start the broadcast! Hakko's extrem...,,https://shared.akamai.steamstatic.com/store_it...,...,0,0,0 - 20000,0,0,0,0,0,1,[]
3631080,Maze Quest VR,"Apr 24, 2025",0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,,https://shared.akamai.steamstatic.com/store_it...,...,0,0,0 - 20000,0,0,0,0,0,0,[]

In [7]:
df_json.shape

(122611, 42)

In [8]:
df_json["genres"].head()

2539430                             []
496350                     [Adventure]
1034400                       [Casual]
3292190    [Casual, Indie, Simulation]
3631080         [Action, Early Access]
Name: genres, dtype: object

A csv fájlhoz hasonlóan, a műfajok itt is felsorolásként vannak megadva.

In [9]:
bad_values = ["", "null", "n/a", "none", "na", "[]"]

df_json.replace(["", "[]", "null", "N/A", "None", "NaN"], pd.NA, inplace=True)

In [10]:
df_json.isnull().sum()

name                             1
release_date                     0
required_age                     0
price                            0
dlc_count                        0
detailed_description          8420
about_the_game                8448
short_description             8309
reviews                     110541
header_image                    81
website                      72935
support_url                  68441
support_email                22252
windows                          0
mac                              0
linux                            0
metacritic_score                 0
metacritic_url              118355
achievements                     0
recommendations                  0
notes                       100153
supported_languages              0
full_audio_languages             0
packages                         0
developers                       0
publishers                       0
categories                       0
genres                           0
screenshots                      0
movies                           0
user_score                       0
score_rank                  122571
positive                         0
negative                         0
estimated_owners                 0
average_playtime_forever         0
average_playtime_2weeks          0
median_playtime_forever          0
median_playtime_2weeks           0
discount                         0
peak_ccu                         0
tags                             0
dtype: int64

In [11]:
missing_pct = df_json.isnull().sum()/len(df_json)

kept_cols = missing_pct[missing_pct < 0.5].index

df_json = df_json[kept_cols]
df_json.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122611 entries, 2539430 to 4141790
Data columns (total 36 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   name                      122610 non-null  object
 1   release_date              122611 non-null  object
 2   required_age              122611 non-null  int64
 3   price                     122611 non-null  float64
 4   dlc_count                 122611 non-null  int64
 5   detailed_description      114191 non-null  object
 6   about_the_game            114163 non-null  object
 7   short_description         114302 non-null  object
 8   header_image              122530 non-null  object
 9   support_email             100359 non-null  object
 10  windows                   122611 non-null  bool
 11  mac                       122611 non-null  bool
 12  linux                     122611 non-null  bool
 13  metacritic_score          122611 non-null  int64
 14  achievements              122611 non-null  int64
 15  recommendations           122611 non-null  int64
 16  supported_languages       122611 non-null  object
 17  full_audio_languages      122611 non-null  object
 18  packages                  122611 non-null  object
 19  developers                122611 non-null  object
 20  publishers                122611 non-null  object
 21  categories                122611 non-null  object
 22  genres                    122611 non-null  object
 23  screenshots               122611 non-null  object
 24  movies                    122611 non-null  object
 25  user_score                122611 non-null  int64
 26  positive                  122611 non-null  int64
 27  negative                  122611 non-null  int64
 28  estimated_owners          122611 non-null  object
 29  average_playtime_forever  122611 non-null  int64
 30  average_playtime_2weeks   122611 non-null  int64
 31  median_playtime_forever   122611 non-null  int64
 32  median_playtime_2weeks    122611 non-null  int64
 33  discount                  122611 non-null  int64
 34  peak_ccu                  122611 non-null  int64
 35  tags                      122611 non-null  object
dtypes: bool(3), float64(1), int64(14), object(18)
memory usage: 32.2+ MB

Eldobtam az oszlopokat, ahol az adatok legalább fele hiányos volt. Feltöltöm a szöveges null adatokat, de a numerikusokat meghagyom.

In [12]:
object_cols = df_json.select_dtypes(include=['object']).columns.tolist()

df_json[object_cols] =df_json[object_cols].fillna("Unknown")

df_json.isnull().sum()

name                        0
release_date                0
required_age                0
price                       0
dlc_count                   0
detailed_description        0
about_the_game              0
short_description           0
header_image                0
support_email               0
windows                     0
mac                         0
linux                       0
metacritic_score            0
achievements                0
recommendations             0
supported_languages         0
full_audio_languages        0
packages                    0
developers                  0
publishers                  0
categories                  0
genres                      0
screenshots                 0
movies                      0
user_score                  0
positive                    0
negative                    0
estimated_owners            0
average_playtime_forever    0
average_playtime_2weeks     0
median_playtime_forever     0
median_playtime_2weeks      0
discount                    0
peak_ccu                    0
tags                        0
dtype: int64

In [13]:
def fix_empty_lists(val):
    bad_values = ["", "[]", "null", "n/a", "none", "na", "nan"]
    
    if isinstance(val, list):
        cleaned_list = [item for item in val if str(item).strip().lower() not in bad_values]
        
        if len(cleaned_list) == 0:
            return ["Unknown"]
        
        return cleaned_list
        
    return val

list_columns = ['genres', 'developers', 'publishers']

for col in list_columns:
    df_json[col] = df_json[col].apply(fix_empty_lists)

df_json[['genres', 'developers']].head(15)

                                    genres              developers
2539430                          [Unknown]               [Unknown]
496350                         [Adventure]                [minori]
1034400                           [Casual]           [Somer Games]
3292190        [Casual, Indie, Simulation]                 [유진게임즈]
3631080             [Action, Early Access]  [Reality Expanded LLC]
1654170                [Action, Adventure]               [Ignibit]
1934300             [Simulation, Strategy]      [Veitikka Studios]
700340                     [Action, Indie]    [Summer Bear Studio]
1157670                    [Casual, Indie]       [Matheus Bigatão]
1540330  [Action, Casual, Indie, Strategy]                 [Airem]
1946890                          [Unknown]               [Unknown]
1108640                 [Adventure, Indie]           [Angry games]
1025440                         [Strategy]      [Owned by Gravity]
2113450                    [Casual, Indie]    [9 Eyes Game Studio]
2922740         [Adventure, Casual, Indie]             [LuuuLuuuL]

A numerikus értékeknél sincsenek végül null-értékek, valószínűleg azért, mert az alap datasetben 0-ként voltak reprezentálva.

Az első oszlop most indexként van jelen, de a csv fájlban AppID néven van.

In [14]:
df_json.index.name = "appID"
df_json.reset_index(inplace=True)

In [15]:
# dim_games tábla
dim_games = df_json[["appID", "name", "required_age", "about_the_game"]].rename(columns={"appID": "game_id"})
dim_games.head()

,game_id,name,required_age,about_the_game
0,2539430,Black Dragon Mage Playtest,0,Unknown
1,496350,Supipara - Chapter 1 Spring Has Come!,0,"Springtime, April: when the cherry trees come ..."
2,1034400,Mystery Solitaire The Black Raven,0,"Immerse yourself in the most beloved, mystical..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,0,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ..."
4,3631080,Maze Quest VR,0,Its not just a Maze; its a Quest! Enter the ca...

In [16]:
df_json["developers"].head(20)

0                                          [Unknown]
1                                           [minori]
2                                      [Somer Games]
3                                            [유진게임즈]
4                             [Reality Expanded LLC]
5                                          [Ignibit]
6                                 [Veitikka Studios]
7                               [Summer Bear Studio]
8                                  [Matheus Bigatão]
9                                            [Airem]
10                                         [Unknown]
11                                     [Angry games]
12                                [Owned by Gravity]
13                              [9 Eyes Game Studio]
14                                       [LuuuLuuuL]
15    [Witching Hour Entertainment LLC, LarsMidnatt]
16                                            [ZENO]
17                                  [Accolade, Inc.]
18                                   [Saku Hållfast]
19                                    [Cat Paw Game]
Name: developers, dtype: object

In [17]:
# dim_developers tábla
# mivel van olyan játék aminek több fejlesztője van, az elsőt tartom meg a felsoroltak közül
df_json["developer_name"] = df_json["developers"].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else x)

dim_developers = df_json[["developer_name"]].drop_duplicates().dropna()

dim_developers["developer_id"] = range(1, len(dim_developers) + 1)

dim_developers.head()

         developer_name  developer_id
0               Unknown             1
1                minori             2
2           Somer Games             3
3                 유진게임즈             4
4  Reality Expanded LLC             5

In [18]:
df_json["publishers"].head(20)

0                               [Unknown]
1                            [MangaGamer]
2                                [8floor]
3                                 [유진게임즈]
4                  [Reality Expanded LLC]
5               [Ignibit, Madmind Studio]
6                          [Matrix Games]
7                    [Summer Bear Studio]
8                       [Matheus Bigatão]
9                                 [Airem]
10                              [Unknown]
11                                [Total]
12                      [Slitherine Ltd.]
13    [9 Eyes Game Studio, Stately Snail]
14                            [LuuuLuuuL]
15      [Witching Hour Entertainment LLC]
16                                 [ZENO]
17             [Atari, Nightdive Studios]
18                        [Saku Hållfast]
19                     [Shark Shark Game]
Name: publishers, dtype: object

In [19]:
# dim_publishers tábla
# mivel van olyan játék aminek több kiadója van, az elsőt tartom meg a felsoroltak közül
df_json["publisher_name"] = df_json["publishers"].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else x)

dim_publishers = df_json[["publisher_name"]].drop_duplicates().dropna()

dim_publishers["publisher_id"] = range(1, len(dim_publishers) + 1)

dim_publishers.head()

         publisher_name  publisher_id
0               Unknown             1
1            MangaGamer             2
2                8floor             3
3                 유진게임즈             4
4  Reality Expanded LLC             5

--

In [20]:
# dim_date tábla
df_json["release_date_parsed"] = pd.to_datetime(df_json["release_date"], errors='coerce')

unique_dates = df_json[["release_date_parsed"]].dropna().drop_duplicates()
dim_date = unique_dates.rename(columns={"release_date_parsed" : "release_date"})
dim_date["date_id"] = range(1, len(dim_date) + 1)
dim_date["release_year"] = dim_date["release_date"].dt.year
dim_date["release_month"] = dim_date["release_date"].dt.month
dim_date["release_day"] = dim_date["release_date"].dt.day

dim_date.head()

  release_date  date_id  release_year  release_month  release_day
0   2023-08-01        1          2023              8            1
1   2016-07-29        2          2016              7           29
2   2019-05-06        3          2019              5            6
3   2024-10-31        4          2024             10           31
4   2025-04-24        5          2025              4           24

--

Első ötletnek minden műfaj első entry-jét tartottam volna meg, de mivel névsorban vannak felsorolva, ez nem a legjellemzőbb minden játékra, és az alfabetikusan hamarabb levő szavak többször fordulnának elő mint amik hátrébb vannak. Ezért inkább a "bridge table" megoldást alkalmazom.

In [21]:
# minden műfajt szétválasztok, és megszűntetem a duplikációkat
all_genres = df_json["genres"].explode().unique()

dim_genres = pd.DataFrame(all_genres, columns=["genre_name"]).dropna()
dim_genres = dim_genres.sort_values("genre_name").reset_index(drop=True)

# 1-től kezdődő indexek
dim_genres["genre_id"] = dim_genres.index + 1

dim_genres.head(50)

               genre_name  genre_id
0               360 Video         1
1              Accounting         2
2                  Action         3
3               Adventure         4
4    Animation & Modeling         5
5        Audio Production         6
6                  Casual         7
7   Design & Illustration         8
8             Documentary         9
9            Early Access        10
10              Education        11
11               Episodic        12
12           Free To Play        13
13       Game Development        14
14                   Gore        15
15                  Indie        16
16  Massively Multiplayer        17
17                  Movie        18
18                 Nudity        19
19          Photo Editing        20
20                    RPG        21
21                 Racing        22
22         Sexual Content        23
23                  Short        24
24             Simulation        25
25      Software Training        26
26                 Sports        27
27               Strategy        28
28               Tutorial        29
29                Unknown        30
30              Utilities        31
31       Video Production        32
32                Violent        33
33         Web Publishing        34

In [ ]:
# bridge_game_genres tábla
temp = df_json[["appID", "genres"]].copy()
temp = temp.explode("genres")
temp = temp.rename(columns={"genres": "genre_name"})
temp = temp.rename(columns={"appID" : "game_id"})

bridge_game_genres = temp.merge(dim_genres, on="genre_name", how="left")
bridge_game_genres = bridge_game_genres[["game_id", "genre_id"]].dropna().astype(int)

bridge_game_genres.head(10)

   game_id  genre_id
0  2539430        30
1   496350         4
2  1034400         7
3  3292190         7
4  3292190        16
5  3292190        25
6  3631080         3
7  3631080        10
8  1654170         3
9  1654170         4

In [23]:
numeric_cols = df_json.select_dtypes(include=['number']).columns.tolist()

print(f"There are {len(numeric_cols)} numerical columns:")
print(numeric_cols)

There are 16 numerical columns:
['appID', 'required_age', 'price', 'dlc_count', 'metacritic_score', 'achievements', 'recommendations', 'user_score', 'positive', 'negative', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'discount', 'peak_ccu']

In [24]:
df_json[['achievements', 'positive', 'negative', 'average_playtime_forever','discount']].head(50)

# 'achievements', 'positive', 'negative', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'discount', 'peak_ccu'

    achievements  positive  negative  average_playtime_forever  discount
0              0         0         0                         0         0
1              0       252         3                         8        65
2              0        21         3                         0         0
3             19         0         0                         0         0
4              0         0         0                         0         0
5              0         0         0                         0         0
6              0       117        13                       675        10
7              0         0         0                         0         0
8              9        28         4                         0         0
9            100        19         6                         0         0
10             0         0         0                         0         0
11             0        47         6                         0         0
12            77      1025       210                       489         0
13            13        64         2                         0        70
14             5        34        10                         0        66
15             0         0         0                         0         0
16            12         2         0                         0         0
17             0        74        35                       203         0
18            17         0         0                         0         0
19            35         0         0                        88         0
20             0         0         0                         0         0
21            66        55        14                       480         0
22            21         0         4                         0         0
23             0         0         0                         0         0
24             3         0         0                         0         0
25             0         0         0                         0         0
26            11     11367       831                       342        80
27             0       144        35                       111         0
28             5         6         0                         0         0
29             0         5         0                         0         0
30            39        75        34                         0         0
31             0         7        15                         0         0
32            24        95         2                         0         0
33             2         5         0                         0         0
34            45       196       104                        88         0
35             0        12         0                         0         0
36             0         0         0                         0         0
37             1         1         1                         0         0
38             0        10         2                         0        80
39             0         0         0                         0         0
40             0        26         9                         0         0
41             9        39         4                       220         0
42            32       330        65                       183         0
43             0         0         0                         0         0
44             1         0         0                         0         0
45            13         0         0                         0         0
46             0         0         0                         0         0
47             0         0         0                         0         0
48            16        31         3                         0         0
49             0         3         0                         0         0

In [25]:
# fact_game_statistics tábla
fact_temp = df_json.merge(dim_developers, left_on="developer_name", right_on="developer_name", how="left")
fact_temp = fact_temp.merge(dim_publishers, left_on="publisher_name", right_on="publisher_name", how="left")
fact_temp = fact_temp.merge(dim_date, left_on="release_date_parsed", right_on="release_date", how="left")

fact_game_statistics = fact_temp[[
    "appID",
    "developer_id",
    "publisher_id",
    "date_id",
    "price",
    "achievements",
    "average_playtime_forever",
    "discount", 
    "peak_ccu"
]]

fact_game_statistics = fact_game_statistics.rename(columns={"appID": "game_id"})
fact_game_statistics["discount"] = fact_game_statistics["discount"] * 0.01

fact_game_statistics.head()

,game_id,developer_id,publisher_id,date_id,price,achievements,average_playtime_forever,discount,peak_ccu
0,2539430,1,1,1,0.00,0,0,0.00,0
1,496350,2,2,2,5.24,0,8,0.65,0
2,1034400,3,3,3,4.99,0,0,0.00,0
3,3292190,4,4,4,8.99,19,0,0.00,1
4,3631080,5,5,5,4.99,0,0,0.00,0

In [26]:
dim_games.to_csv("../data/processed/dim_games.csv", index=False)
dim_developers.to_csv("../data/processed/dim_developers.csv", index=False)
dim_publishers.to_csv("../data/processed/dim_publishers.csv", index=False)
dim_date.to_csv("../data/processed/dim_date.csv", index=False)
dim_genres.to_csv("../data/processed/dim_genres.csv", index=False)
bridge_game_genres.to_csv("../data/processed/bridge_game_genres.csv", index=False)
fact_game_statistics.to_csv("../data/processed/fact_game_statistics.csv", index=False)